<?php

namespace AnimalsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OiseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OiseauRepository extends EntityRepository
{
}
