animals_homepage:
    path:     /
    defaults: { _controller: AnimalsBundle:Default:index }

animals_edit:
    path:     /edit/{id}
    defaults: { _controller: AnimalsBundle:Default:edit }
    requirements:
        id: '\d+'

animals_add:
    path:     /add
    defaults: { _controller: AnimalsBundle:Default:add }

animals_delete:
    path:     /delete/{id}
    defaults: { _controller: AnimalsBundle:Default:delete }
    requirements:
        id: '\d+'
